# Generated by Django 4.1 on 2022-10-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0005_autor_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
