# Generated by Django 4.1 on 2022-09-04 00:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='conteniod',
        ),
        migrations.AddField(
            model_name='post',
            name='contenido',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Contenido'),
            preserve_default=False,
        ),
    ]
