# Generated by Django 4.1.1 on 2022-09-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagen_referencia',
            new_name='imagen_referencial',
        ),
        migrations.AddField(
            model_name='autor',
            name='imagen_referencia',
            field=models.ImageField(blank=True, null=True, upload_to='autores/', verbose_name='Imagen Referencial'),
        ),
    ]
