# Generated by Django 4.1.1 on 2022-09-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_imagen_referencia_autor_imagen_referencial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='web',
            old_name='Nosotros',
            new_name='nosotros',
        ),
    ]
